### PR TITLE
Fix #1259 - Do not fail because on uncommitted records if the consumer do not own the partition anymore

### LINKED ISSUE #1259: Kafka: Liveness probe fails after rebalance took place
I'm using quarkus 2.0.0.CR3 and therefore smallrye kafka 3.3.2

Consuming a high velocity stream with multiple consumers in a group.
Using `commit-strategy: throttled`

Incoming channel is annotated like this:
```
  @Incoming("events")
  @Blocking
  @Acknowledgment(Strategy.MANUAL)
```
In here I have some async operation (Elasticsearch BulkPorcessor) etc. which ack / nacks the messages.

When a new consumer joins on the others I get

`SRMSG18239: Acked record 8041153253 on group 'group' was ignored because the topic partition 'topic-4' was revoked for this instance. Record will likely be processed again.`

I'm ok with some duplicates, so far so good.

After a few seconds on the next livenes check I get

`SRHCK01001: Reporting health down status: {"status":"DOWN","checks":[{"name":"SmallRye Reactive Messaging - liveness check","status":"DOWN","data":{"events":"[KO] - Too Many Messages without acknowledgement in topic topic (partition:4), last committed offset is 7980556233Too Many Messages without acknowledgement in topic topic (partition:7), last committed offset is 7868958352"}}]}`

I cannot see any other errors or nacked messages. It looks like the messages which are acked from the aync operation after the rebalance took place count into the number causing 'Too Many Messages without acknowledgement' and cause the liveness to get down. Eventually they are also leaking memory.

Am I doing something wrong?
Is there a way to get rid of these messages which are acked on a revoked partition?

### PR DESCRIPTION
**Pull request by cescoffier**
After a rebalance, ignore uncommitted records on revoked partitions, they will be cleared eventually.
The main change is the tracking of the assignments and checking if the partition is still assigned to the consumer before throwing the exception.

### CODE REVIEW

File: smallrye-reactive-messaging-kafka/src/test/java/io/smallrye/reactive/messaging/kafka/commit/DeprecatedCommitStrategiesTest.java [hunk 1]
```diff
@@ -323,6 +326,7 @@ void testThrottledStrategyWithTooManyUnackedMessages() throws Exception {
 
         consumer.schedulePollTask(() -> {
             consumer.rebalance(offsets.keySet());
+            source.getCommitHandler().partitionsAssigned(offsets.keySet());
```
Comment (Ladicek) [inline smallrye-reactive-messaging-kafka/src/test/java/io/smallrye/reactive/messaging/kafka/commit/DeprecatedCommitStrategiesTest.java:329]: I'd expect identical changes in the `CommitStrategiesTest` -- this one is a copy of that using `@Named` instead of `@Identifier`.

File: smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/commit/KafkaThrottledLatestProcessedCommit.java [hunk 2]
```diff
@@ -378,6 +380,11 @@ boolean hasTooManyMessagesWithoutAck() {
             return false;
         }
 
+        private boolean isStillAssigned() {
+            // If the topic/partition is not assigned to us already, the store will be cleared eventually.
+            return assignments.contains(topicPartition);
```
Comment (Ladicek) [inline smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/commit/KafkaThrottledLatestProcessedCommit.java:385]: Don't `offsetStores` include the same information? In other words, could this method be implemented as `return offsetStore.containsKey(topicPartition);`?

Comment (cescoffier) [reply smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/commit/KafkaThrottledLatestProcessedCommit.java:385]: No, because the deletion happens asynchronously, and so there is a window where it would still be there, while not being assigned anymore.

**Comment by Ladicek** [comment]
Can't say I truly understand the code, but the logic seems fine. Added just 2 small comments.

File: smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/commit/KafkaThrottledLatestProcessedCommit.java (hunk 2 above)
Comment (Ladicek) [reply smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/commit/KafkaThrottledLatestProcessedCommit.java:385]: Ah interesting!

File: smallrye-reactive-messaging-kafka/src/test/java/io/smallrye/reactive/messaging/kafka/commit/DeprecatedCommitStrategiesTest.java (hunk 1 above)
Comment (cescoffier) [reply smallrye-reactive-messaging-kafka/src/test/java/io/smallrye/reactive/messaging/kafka/commit/DeprecatedCommitStrategiesTest.java:330]: Fixed.

FYI, the mock consumer does not handle rebalance (does not call the listener) but we need to call rebalance to set up the assigned partitions. So adding this second invocation simulates a "real" rebalance.

File: smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/commit/KafkaThrottledLatestProcessedCommit.java [hunk 3]
```diff
@@ -47,6 +47,7 @@
     private final int unprocessedRecordMaxAge;
     private final int autoCommitInterval;
     private volatile long timerId = -1;
+    private final Collection<TopicPartition> assignments = new CopyOnWriteArrayList<>();
```
Comment (Ladicek) [inline smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/commit/KafkaThrottledLatestProcessedCommit.java:50]: Just today morning, I realized I saw `CopyOnWriteArrayList` here. I think `Collections.newSetFromMap(new ConcurrentHashMap<>())` would probably be more appropriate, given that you only use `addAll`, `removeAll` and `contains`.

Comment (cescoffier) [reply smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/commit/KafkaThrottledLatestProcessedCommit.java:50]: Hum, very good point! 
Fancy a PR (this one was already merged).

Comment (Ladicek) [reply smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/commit/KafkaThrottledLatestProcessedCommit.java:50]: Sure, gimme a sec :-)

Comment (Ladicek) [reply smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/commit/KafkaThrottledLatestProcessedCommit.java:50]: #1261#1261
