### PR TITLE
Pulsar force schema fetch on pulsar-client-thread for all schema requiring schema info fetching

### LINKED ISSUE #2493: Deadlock when using Avro schema with Pulsar connctor
When consuming message from pulsar incoming topic with Avro schema it might cause a deadlock when checking schema version via pulsar client. Pulsar client is not fully async and fetching schema version is done on `event` loop. This causes deadlock:
```
io.vertx.core.VertxException: Thread blocked
	at java.base@17.0.10/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17.0.10/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
	at java.base@17.0.10/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
	at java.base@17.0.10/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465)
	at java.base@17.0.10/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436)
	at java.base@17.0.10/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
	at java.base@17.0.10/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2072)
	at app//org.apache.pulsar.client.impl.schema.reader.AbstractMultiVersionReader.getSchemaInfoByVersion(AbstractMultiVersionReader.java:118)
	at app//org.apache.pulsar.client.impl.schema.reader.MultiVersionAvroReader.loadReader(MultiVersionAvroReader.java:45)
	at app//org.apache.pulsar.client.impl.schema.reader.AbstractMultiVersionReader$1.load(AbstractMultiVersionReader.java:51)
	at app//org.apache.pulsar.client.impl.schema.reader.AbstractMultiVersionReader$1.load(AbstractMultiVersionReader.java:48)
	at app//com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3571)
	at app//com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2313)
	at app//com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2190)
	at app//com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2080)
	at app//com.google.common.cache.LocalCache.get(LocalCache.java:4012)
	at app//com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4035)
	at app//com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5013)
	at app//org.apache.pulsar.client.impl.schema.reader.AbstractMultiVersionReader.getSchemaReader(AbstractMultiVersionReader.java:82)
	at app//org.apache.pulsar.client.impl.schema.reader.AbstractMultiVersionReader.read(AbstractMultiVersionReader.java:73)
	at app//org.apache.pulsar.client.impl.schema.AbstractStructSchema.decode(AbstractStructSchema.java:90)
	at app//org.apache.pulsar.client.impl.MessageImpl.decodeBySchema(MessageImpl.java:505)
	at app//org.apache.pulsar.client.impl.MessageImpl.decode(MessageImpl.java:486)
	at app//org.apache.pulsar.client.impl.MessageImpl.getValue(MessageImpl.java:471)
	at app//io.smallrye.reactive.messaging.pulsar.PulsarIncomingMessage.getPayload(PulsarIncomingMessage.java:40)
	at app//org.eclipse.microprofile.reactive.messaging.Message.withMetadata(Message.java:408)
```

### PR DESCRIPTION
**Pull request by ozangunalp**
Fixes #2493

### CODE REVIEW

**Review by cescoffier — DISMISSED** [review]

File: smallrye-reactive-messaging-pulsar/src/main/java/io/smallrye/reactive/messaging/pulsar/PulsarIncomingChannel.java [hunk 1]
```diff
@@ -115,8 +115,8 @@ public PulsarIncomingChannel(PulsarClient client, Vertx vertx, Schema<T> schema,
                     .until(m -> closed.get())
                     .plug(msgMulti -> {
                         // Calling getValue on the pulsar-client-internal thread to make sure the SchemaInfo is fetched
-                        if (schema instanceof AutoConsumeSchema || schema instanceof KeyValueSchema) {
-                            return msgMulti.onItem().call(msg -> Uni.createFrom().item(msg::getValue));
+                        if (schema.requireFetchingSchemaInfo()) {
```
Comment (marekczajkowski) [inline smallrye-reactive-messaging-pulsar/src/main/java/io/smallrye/reactive/messaging/pulsar/PulsarIncomingChannel.java:118]: The same mechanism should be used for batch see line 141

**Review by marekczajkowski — CHANGES_REQUESTED** [review]
Add same mechanism for batch case

**Comment by ozangunalp** [comment]
@marekczajkowski thanks for pointing it out. I pushed the fix.
