### PR TITLE
Recreate a sender when the link is closed by the remote party.

### LINKED ISSUE #1588: AMQP - Intermittent errors sending messages to Azure Service Bus due to closed idle connections
I have a Quarkus 2.6.3 application that sends messages via an `Emitter` to Azure Service Bus
It uses smallrye-reactive-messaging-amqp 3.13.0

Azure Service Bus disconnects idle connections after 5 minutes.  That's just how it is.
Right after the Azure Service Bus drops the idle connection, attempts to send a message fail with the Exception below.
Eventually the system recovers and is able to send messages again, but this leaves it in bad state for several minutes.

**Code:**
```
@ApplicationScoped
public class MessageSender {
	
    @Inject
    @Channel("my-queue")
    Emitter<MyJsonPayload> emitter;
	
    public void sendMessage() {
         emitter.send(createPayload());
    }
}
```

**Configuration:**
```
amqp-host=my-namespace.servicebus.windows.net
amqp-port=5671
amqp-use-ssl=true
amqp-username=*********
amqp-password=*********
amqp-reconnect-interval=5

mp.messaging.outgoing.my-queue.connector=smallrye-amqp
mp.messaging.outgoing.my-queue.use-anonymous-sender=false
mp.messaging.outgoing.my-queue.address=my-queue
```

**Exception**:
```
2022-01-28 15:57:34,221 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-6) Uncaught exception received by Vert.x: java.lang.IllegalStateException: send not allowed after the sender is closed.
	at org.apache.qpid.proton.engine.impl.SenderImpl.sendNoCopy(SenderImpl.java:86)
	at io.vertx.proton.impl.ProtonSenderImpl.send(ProtonSenderImpl.java:91)
	at io.vertx.proton.impl.ProtonSenderImpl.send(ProtonSenderImpl.java:56)
	at io.vertx.amqp.impl.AmqpSenderImpl.lambda$doSend$6(AmqpSenderImpl.java:183)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

This is preceded by this stack-trace that indicates that the connection was closed by Azure Service Bus:
```
2022-01-28 15:05:15,894 ERROR [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-0) SRMSG16214: AMQP Connection failure: java.lang.Exception: Connection disconnected
	at io.vertx.amqp.impl.AmqpConnectionImpl.onDisconnect(AmqpConnectionImpl.java:158)
	at io.vertx.amqp.impl.AmqpConnectionImpl.lambda$null$3(AmqpConnectionImpl.java:113)
	at io.vertx.proton.impl.ProtonConnectionImpl.lambda$getDefaultSession$6(ProtonConnectionImpl.java:263)
	at io.vertx.proton.impl.ProtonSessionImpl.fireRemoteClose(ProtonSessionImpl.java:276)
	at io.vertx.proton.impl.ProtonTransport.handleSocketBuffer(ProtonTransport.java:135)
	at io.vertx.core.net.impl.NetSocketImpl.lambda$new$1(NetSocketImpl.java:98)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:130)
	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:418)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:274)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:394)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:156)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1371)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

The remote connection closure needs to be handled more gracefully.

Unfortunately I can't create a test-case to reproduce this.  It's intermittent, and involves closing the connection by the broker.

### PR DESCRIPTION
**Pull request by cescoffier**
Before sending a message, retrieve the sender. If already created, verify that the connection is still open **and** that the link is still open. Indeed, Azure Service Hub closes the link (but keeps the connection opened).
In this case, we close the sender and recreate one.

~~This PR contains a hack waiting for https://github.com/vert-x3/vertx-amqp-client/pull/78.~~ Method shipped with Vert.x 4.2.5. 

Fix #1588.

### CODE REVIEW

File: smallrye-reactive-messaging-amqp/src/main/java/io/smallrye/reactive/messaging/amqp/AmqpConnector.java [hunk 1]
```diff
@@ -256,34 +257,41 @@ void init() {
...
+        Uni<AmqpSender> getSender = Uni.createFrom().deferred(() -> {
+
+            // If we already have a sender, use it.
+            AmqpSender current = sender.get();
+            if (current != null && !current.connection().isDisconnected()) {
+                if (isLinkOpen(current)) {
+                    return Uni.createFrom().item(current);
+                } else {
+                    // link closed, close the sender, and recreate one.
+                    current.closeAndForget();
```
Comment (ozangunalp) [inline smallrye-reactive-messaging-amqp/src/main/java/io/smallrye/reactive/messaging/amqp/AmqpConnector.java:269]: Do we need to put the channel to false on `opened` map ?

**Review by ozangunalp — COMMENTED** [review]
Don't we need the same thing for the receiver?

File: smallrye-reactive-messaging-amqp/src/main/java/io/smallrye/reactive/messaging/amqp/AmqpConnector.java (hunk 1 above)
Comment (cescoffier) [reply smallrye-reactive-messaging-amqp/src/main/java/io/smallrye/reactive/messaging/amqp/AmqpConnector.java:269]: No, because if we do, we would be considered unhealthy. It will be switched to false if we cannot re-open the link.

Comment (ozangunalp) [reply smallrye-reactive-messaging-amqp/src/main/java/io/smallrye/reactive/messaging/amqp/AmqpConnector.java:269]: 👍

**Comment by cescoffier** [comment]
I've rebased the branch to see if the latest CI fixes make it "green"

**Review by ozangunalp — APPROVED** [review]
