### PR TITLE
Fix broken MQTT client by implementing a reconnect "session"

### LINKED ISSUE #1181: When an MQTT connection dies, it fails with a NPE and never reconnects
Assuming there is successfully connected MQTT connection, which then just dies. In the log you can see a NPE (`NullPointerException') and the client never reconnects.

~~~
2021-04-28 12:50:12,161 ERROR [io.sma.rea.mes.mqtt] (vert.x-eventloop-thread-0) SRMSG17103: An error has been caught while sending a MQTT message to the broker: java.lang.NullPointerException
~~~

<details>
<summary>Full exception stack trace</summary>

~~~
2021-04-28 12:50:12,161 ERROR [io.sma.rea.mes.mqtt] (vert.x-eventloop-thread-0) SRMSG17103: An error has been caught while sending a MQTT message to the broker: java.lang.NullPointerException
	at io.vertx.mqtt.impl.MqttClientImpl.write(MqttClientImpl.java:785)
	at io.vertx.mqtt.impl.MqttClientImpl.disconnect(MqttClientImpl.java:298)
	at io.vertx.mqtt.impl.MqttClientImpl.disconnect(MqttClientImpl.java:279)
	at io.vertx.mutiny.mqtt.MqttClient.disconnectAndForget(MqttClient.java:564)
	at io.smallrye.reactive.messaging.mqtt.MqttSink.lambda$new$4(MqttSink.java:78)
	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
	at io.smallrye.mutiny.operators.multi.MultiOnCompletionInvoke$MultiOnCompletionInvokeProcessor.onCompletion(MultiOnCompletionInvoke.java:36)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.handleTerminationIfDone(MultiFlatMapOp.java:514)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.ifDoneOrCancelled(MultiFlatMapOp.java:486)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.drainLoop(MultiFlatMapOp.java:286)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.drain(MultiFlatMapOp.java:266)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.onCompletion(MultiFlatMapOp.java:220)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.handleTerminationIfDone(MultiFlatMapOp.java:514)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.ifDoneOrCancelled(MultiFlatMapOp.java:486)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.drainLoop(MultiFlatMapOp.java:286)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.drain(MultiFlatMapOp.java:266)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.onCompletion(MultiFlatMapOp.java:220)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onComplete(MultiSubscriber.java:83)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onComplete(SafeSubscriber.java:167)
	at io.smallrye.mutiny.helpers.HalfSerializer.onComplete(HalfSerializer.java:75)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onCompletion(StrictMultiSubscriber.java:95)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onComplete(MultiSubscriber.java:83)
	at io.smallrye.mutiny.streams.utils.ConnectableProcessor.onComplete(ConnectableProcessor.java:129)
	at org.eclipse.microprofile.reactive.streams.operators.CompletionSubscriber$1DefaultCompletionSubscriber.onComplete(CompletionSubscriber.java:95)
	at org.eclipse.microprofile.reactive.streams.operators.CompletionSubscriber$1DefaultCompletionSubscriber.onComplete(CompletionSubscriber.java:95)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onComplete(SafeSubscriber.java:167)
	at io.smallrye.mutiny.helpers.HalfSerializer.onComplete(HalfSerializer.java:75)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onCompletion(StrictMultiSubscriber.java:95)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onComplete(MultiSubscriber.java:83)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onComplete(SafeSubscriber.java:167)
	at io.smallrye.mutiny.helpers.HalfSerializer.onComplete(HalfSerializer.java:75)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onCompletion(StrictMultiSubscriber.java:95)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.handleTerminationIfDone(MultiFlatMapOp.java:514)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.ifDoneOrCancelled(MultiFlatMapOp.java:486)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.drainLoop(MultiFlatMapOp.java:286)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.drain(MultiFlatMapOp.java:266)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.onCompletion(MultiFlatMapOp.java:220)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onComplete(MultiSubscriber.java:83)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onComplete(SafeSubscriber.java:167)
	at io.smallrye.mutiny.helpers.HalfSerializer.onComplete(HalfSerializer.java:75)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onCompletion(StrictMultiSubscriber.java:95)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onComplete(MultiSubscriber.java:83)
	at io.smallrye.mutiny.streams.utils.ConnectableProcessor.onComplete(ConnectableProcessor.java:129)
	at io.smallrye.mutiny.streams.utils.WrappedProcessor.onComplete(WrappedProcessor.java:54)
	at io.smallrye.mutiny.helpers.HalfSerializer.onComplete(HalfSerializer.java:75)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onCompletion(StrictMultiSubscriber.java:95)
	at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.onCompletion(MultiOperatorProcessor.java:74)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onComplete(MultiSubscriber.java:83)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onComplete(SafeSubscriber.java:167)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onComplete(SafeSubscriber.java:167)
	at io.smallrye.mutiny.helpers.HalfSerializer.onComplete(HalfSerializer.java:75)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onCompletion(StrictMultiSubscriber.java:95)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onComplete(MultiSubscriber.java:83)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onComplete(SafeSubscriber.java:167)
	at io.smallrye.mutiny.helpers.HalfSerializer.onComplete(HalfSerializer.java:75)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onCompletion(StrictMultiSubscriber.java:95)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.handleTerminationIfDone(MultiFlatMapOp.java:514)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.ifDoneOrCancelled(MultiFlatMapOp.java:486)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.drainLoop(MultiFlatMapOp.java:286)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.drain(MultiFlatMapOp.java:266)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.onCompletion(MultiFlatMapOp.java:220)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onComplete(MultiSubscriber.java:83)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onComplete(SafeSubscriber.java:167)
	at io.smallrye.mutiny.helpers.HalfSerializer.onComplete(HalfSerializer.java:75)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onCompletion(StrictMultiSubscriber.java:95)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onComplete(MultiSubscriber.java:83)
	at io.smallrye.mutiny.streams.utils.ConnectableProcessor.onComplete(ConnectableProcessor.java:129)
	at io.smallrye.mutiny.streams.utils.WrappedProcessor.onComplete(WrappedProcessor.java:54)
	at io.smallrye.mutiny.helpers.HalfSerializer.onComplete(HalfSerializer.java:75)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onCompletion(StrictMultiSubscriber.java:95)
	at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.onCompletion(MultiOperatorProcessor.java:74)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onComplete(MultiSubscriber.java:83)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onComplete(SafeSubscriber.java:167)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onComplete(SafeSubscriber.java:167)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onComplete(SafeSubscriber.java:167)
	at io.smallrye.mutiny.helpers.HalfSerializer.onComplete(HalfSerializer.java:75)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onCompletion(StrictMultiSubscriber.java:95)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onComplete(MultiSubscriber.java:83)
	at io.smallrye.mutiny.operators.multi.multicast.MultiPublishOp$PublishSubscriber.isEmptyOrCompleted(MultiPublishOp.java:315)
	at io.smallrye.mutiny.operators.multi.multicast.MultiPublishOp$PublishSubscriber.drain(MultiPublishOp.java:381)
	at io.smallrye.mutiny.operators.multi.multicast.MultiPublishOp$PublishSubscriber.onCompletion(MultiPublishOp.java:195)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onComplete(MultiSubscriber.java:83)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onComplete(SafeSubscriber.java:167)
	at io.smallrye.mutiny.helpers.HalfSerializer.onComplete(HalfSerializer.java:75)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onCompletion(StrictMultiSubscriber.java:95)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onComplete(MultiSubscriber.java:83)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onComplete(SafeSubscriber.java:167)
	at io.smallrye.mutiny.helpers.HalfSerializer.onComplete(HalfSerializer.java:75)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onCompletion(StrictMultiSubscriber.java:95)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.handleTerminationIfDone(MultiFlatMapOp.java:514)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.ifDoneOrCancelled(MultiFlatMapOp.java:486)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.drainLoop(MultiFlatMapOp.java:286)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.drain(MultiFlatMapOp.java:266)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.onCompletion(MultiFlatMapOp.java:220)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onComplete(MultiSubscriber.java:83)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onComplete(SafeSubscriber.java:167)
	at io.smallrye.mutiny.helpers.HalfSerializer.onComplete(HalfSerializer.java:75)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onCompletion(StrictMultiSubscriber.java:95)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onComplete(MultiSubscriber.java:83)
	at io.smallrye.mutiny.streams.utils.ConnectableProcessor.onComplete(ConnectableProcessor.java:129)
	at io.smallrye.mutiny.streams.utils.WrappedProcessor.onComplete(WrappedProcessor.java:54)
	at io.smallrye.mutiny.helpers.HalfSerializer.onComplete(HalfSerializer.java:75)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onCompletion(StrictMultiSubscriber.java:95)
	at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.onCompletion(MultiOperatorProcessor.java:74)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onComplete(MultiSubscriber.java:83)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onComplete(SafeSubscriber.java:167)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onComplete(SafeSubscriber.java:167)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onComplete(SafeSubscriber.java:167)
	at io.smallrye.mutiny.helpers.HalfSerializer.onComplete(HalfSerializer.java:75)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onCompletion(StrictMultiSubscriber.java:95)
	at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.onCompletion(MultiOperatorProcessor.java:74)
	at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.onCompletion(MultiOperatorProcessor.java:74)
	at io.smallrye.mutiny.operators.multi.MultiOnCancellationInvoke$MultiOnCancellationInvokeProcessor.onCompletion(MultiOnCancellationInvoke.java:36)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onComplete(MultiSubscriber.java:83)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToMulti$FlatMapPublisherSubscriber.onComplete(UniOnItemTransformToMulti.java:69)
	at io.smallrye.mutiny.helpers.HalfSerializer.onComplete(HalfSerializer.java:75)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onCompletion(StrictMultiSubscriber.java:95)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onComplete(MultiSubscriber.java:83)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToMulti$FlatMapPublisherSubscriber.onComplete(UniOnItemTransformToMulti.java:69)
	at io.smallrye.mutiny.helpers.HalfSerializer.onComplete(HalfSerializer.java:75)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onCompletion(StrictMultiSubscriber.java:95)
	at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.onCompletion(MultiOperatorProcessor.java:74)
	at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.onCompletion(MultiOperatorProcessor.java:74)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onComplete(MultiSubscriber.java:83)
	at io.smallrye.mutiny.operators.multi.processors.BroadcastProcessor$BroadcastSubscription.onComplete(BroadcastProcessor.java:225)
	at io.smallrye.mutiny.operators.multi.processors.BroadcastProcessor.onComplete(BroadcastProcessor.java:164)
	at io.smallrye.reactive.messaging.mqtt.Clients$ClientHolder.lambda$new$0(Clients.java:64)
	at io.vertx.mqtt.impl.MqttClientImpl.handleClosed(MqttClientImpl.java:806)
	at io.vertx.mqtt.impl.MqttClientImpl.lambda$null$1(MqttClientImpl.java:234)
	at io.vertx.core.net.impl.ConnectionBase.handleClosed(ConnectionBase.java:353)
	at io.vertx.core.net.impl.NetSocketImpl.handleClosed(NetSocketImpl.java:346)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelInactive$3(VertxHandler.java:153)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:221)
	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.handler.stream.ChunkedWriteHandler.channelInactive(ChunkedWriteHandler.java:138)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1106)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
~~~

</details>

### PR DESCRIPTION
**Pull request by ctron**
This is based on the content of PR https://github.com/vert-x3/vertx-mqtt/pull/197

Fixes #1181

### CODE REVIEW

**Comment by ctron** [comment]
Yay, that looks better:

~~~
2021-05-27 18:46:35,300 INFO  [io.ver.mqt.imp.MqttClientImpl] (vert.x-eventloop-thread-0) Connection with mqtt-integration-drogue-dev.apps.wonderful.iot-playground.org:443 established successfully
2021-05-27 18:46:52,376 INFO  [io.dro.iot.dem.int.Receiver] (vert.x-eventloop-thread-0) Received message: CloudEvent{id='ffd2b536-a978-4409-b13c-71454c47d548', source=drogue://drogue%2Dpublic%2Dtemperature/A4%3AC1%3A38%3AA2%3A6D%3A42, type='io.drogue.event.v1', datacontenttype='application/json', dataschema=urn:drogue:iot:temperature, subject='status', time=2021-05-27T16:46:52.311145045Z, data=BytesCloudEventData{value=[123, 34, 116, 101, 109, 112, 34, 58, 32, 50, 54, 46, 55, 44, 32, 34, 104, 117, 109, 34, 58, 32, 52, 52, 44, 32, 34, 98, 97, 116, 116, 34, 58, 32, 57, 53, 125]}, extensions={instance=drogue, knativehistory=iot-channel-kn-channel.drogue-dev.svc.cluster.local, partitionkey=drogue%2Dpublic%2Dtemperature/A4%3AC1%3A38%3AA2%3A6D%3A42, application=drogue-public-temperature, device=A4:C1:38:A2:6D:42}}
2021-05-27 18:47:02,363 INFO  [io.dro.iot.dem.int.Receiver] (pool-1-thread-1) Received message: CloudEvent{id='da31b316-dcd7-433b-970f-829fffeb8846', source=drogue://drogue%2Dpublic%2Dtemperature/A4%3AC1%3A38%3AA2%3A6D%3A42, type='io.drogue.event.v1', datacontenttype='application/json', dataschema=urn:drogue:iot:temperature, subject='status', time=2021-05-27T16:47:02.333709259Z, data=BytesCloudEventData{value=[123, 34, 116, 101, 109, 112, 34, 58, 32, 50, 54, 46, 55, 44, 32, 34, 104, 117, 109, 34, 58, 32, 52, 52, 44, 32, 34, 98, 97, 116, 116, 34, 58, 32, 57, 53, 125]}, extensions={instance=drogue, knativehistory=iot-channel-kn-channel.drogue-dev.svc.cluster.local, application=drogue-public-temperature, partitionkey=drogue%2Dpublic%2Dtemperature/A4%3AC1%3A38%3AA2%3A6D%3A42, device=A4:C1:38:A2:6D:42}}
2021-05-27 18:47:04,574 INFO  [io.sma.rea.mes.mqt.ses.imp.MqttClientSessionImpl] (vert.x-eventloop-thread-0) Connection closed: Connection closed
2021-05-27 18:47:15,637 ERROR [io.ver.mqt.imp.MqttClientImpl] (vert.x-eventloop-thread-0) Can't connect to mqtt-integration-drogue-dev.apps.wonderful.iot-playground.org:443: javax.net.ssl.SSLHandshakeException: Failed to create SSL connection
	at io.vertx.core.net.impl.ChannelProvider$1.userEventTriggered(ChannelProvider.java:129)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
	at io.netty.handler.ssl.SslUtils.handleHandshakeFailure(SslUtils.java:441)
	at io.netty.handler.ssl.SslHandler$7.run(SslHandler.java:2033)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
	at io.netty.handler.ssl.SslHandler$7.run(SslHandler.java:2029)
	... 9 more

2021-05-27 18:47:16,779 INFO  [io.ver.mqt.imp.MqttClientImpl] (vert.x-eventloop-thread-0) Connection with mqtt-integration-drogue-dev.apps.wonderful.iot-playground.org:443 established successfully
2021-05-27 18:47:22,360 INFO  [io.dro.iot.dem.int.Receiver] (pool-1-thread-1) Received message: CloudEvent{id='00891b1b-8858-4186-80cd-75fcfb8aa3b6', source=drogue://drogue%2Dpublic%2Dtemperature/A4%3AC1%3A38%3AA2%3A6D%3A42, type='io.drogue.event.v1', datacontenttype='application/json', dataschema=urn:drogue:iot:temperature, subject='status', time=2021-05-27T16:47:22.330814606Z, data=BytesCloudEventData{value=[123, 34, 116, 101, 109, 112, 34, 58, 32, 50, 54, 46, 55, 44, 32, 34, 104, 117, 109, 34, 58, 32, 52, 52, 44, 32, 34, 98, 97, 116, 116, 34, 58, 32, 57, 53, 125]}, extensions={instance=drogue, knativehistory=iot-channel-kn-channel.drogue-dev.svc.cluster.local, application=drogue-public-temperature, partitionkey=drogue%2Dpublic%2Dtemperature/A4%3AC1%3A38%3AA2%3A6D%3A42, device=A4:C1:38:A2:6D:42}}
~~~

File: smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/MqttSink.java [hunk 1]
```diff
@@ -13,94 +13,83 @@
...
+                    if (client == null) {
+                        client = Clients.getHolder(vertx, options);
+                        // FIXME: add session state listener
+                        client.start();
+                        reference.set(client);
                     }
+
+                    return client.sessionState()
+                            .filter(state -> state != SessionState.CONNECTED)
+                            .map(ignore -> msg).toUni().subscribeAsCompletionStage();
```
Comment (cescoffier) [inline smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/MqttSink.java:52]: That is just waiting for the first item. Is that what you expect?

File: smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/session/impl/MqttClientSessionImpl.java [hunk 2]
```diff
@@ -0,0 +1,672 @@
...
+     */
+    public MqttClientSessionImpl(final Vertx vertx, final MqttClientSessionOptions options) {
+        this.vertx = (VertxInternal) vertx;
+        this.options = options;
+        this.reconnectDelay = options.getReconnectDelay().createProvider();
+    }
+
+    @Override
+    public void start() {
+        this.vertx.runOnContext(x -> doStart());
```
Comment (cescoffier) [inline smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/session/impl/MqttClientSessionImpl.java:89]: The start and stop should return Uni or Future and complete/fail when the action completes/fails

File: smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/session/impl/MqttClientSessionImpl.java [hunk 3]
```diff
@@ -0,0 +1,672 @@
...
+    }
+
+    @Override
+    public SubscriptionState getSubscriptionState(String topicFilter) {
+        return this.subscriptionStates.get(topicFilter);
+    }
+
+    @Override
+    public MqttClientSession subscribe(Map<String, RequestedQoS> topics) {
+        final Map<String, RequestedQoS> finalTopics = new LinkedHashMap<>(topics);
```
Comment (cescoffier) [inline smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/session/impl/MqttClientSessionImpl.java:109]: it would probably be better to report the success as a Future or Uni

File: smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/session/impl/MqttClientSessionImpl.java [hunk 4]
```diff
@@ -0,0 +1,672 @@
...
+        this.vertx.runOnContext(x -> doSubscribe(finalTopics));
+        return this;
+    }
+
+    @Override
+    public MqttClientSession unsubscribe(List<String> topics) {
+        final Set<String> finalTopics = new HashSet<>(topics);
+        this.vertx.runOnContext(x -> doUnsubscribe(finalTopics));
```
Comment (cescoffier) [inline smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/session/impl/MqttClientSessionImpl.java:117]: Same here.

**Review by cescoffier — CHANGES_REQUESTED** [review]

File: smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/MqttSink.java (hunk 1 above)
Comment (ctron) [reply smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/MqttSink.java:52]: My understanding of this part (and I may be wrong here) is that this code get a "client" for a single operation of sending a messages. Closing it later on, when the sending is complete.

If that understanding is correct, then yes, the first event switching to CONNECTED is sufficient. As this waits for the first time the connection is established, and then it sends the message.

If my assumption is not correct, and the client is kept open. Then that part should probably to the "send" method.

File: smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/session/impl/MqttClientSessionImpl.java (hunk 2 above)
Comment (ctron) [reply smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/session/impl/MqttClientSessionImpl.java:89]: There is no real "end" of the operation. That just starts the state machine driving the connection towards "CONNECTED".

**Comment by ctron** [comment]
Ok, I have been thinking a bit about the remarks for start, subscribe, unsubscribe.

Initially my thinking was that this will just record it as a "desired state", and let the state machine try to drive it towards that.

However, the ClientHolder actually provides methods to monitor the state changes, and turn that into Futures/Unis. That could also be done directly be the start/subscribe/unsubscribe methods. Moving that logic there, would that be ok, from your point of view?

**Comment by cescoffier** [comment]
Yes!

**Comment by ctron** [comment]
Ok, that took a bit:

~~~
[INFO] Results:
[INFO] 
[INFO] Tests run: 37, Failures: 0, Errors: 0, Skipped: 0
~~~

I made the changes, and tests look good now.

The PR definitely needs to get squashed :grin:

File: smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/session/impl/MqttClientSessionImpl.java (hunk 3 above)
Comment (ctron) [reply smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/session/impl/MqttClientSessionImpl.java]: Same here.

File: smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/session/impl/MqttClientSessionImpl.java (hunk 4 above)
Comment (ctron) [reply smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/session/impl/MqttClientSessionImpl.java]: And here

**Comment by cescoffier** [comment]
Can you squash?

**Comment by ctron** [comment]
Squashed!

**Comment by cescoffier** [comment]
Thanks, let's see what the CI says and include it. 
It will be part of tomorrow's release.

**Comment by cescoffier** [comment]
Thaks a lot @ctron !
